#%RAML 1.0
title: "Email recognition service"
description: "Email recognition service"
version: "1.0"
protocols:
- "HTTP"
#baseUri: "https://thecontactsapi.restlet.net/v1"
mediaType: application/json

types:
  Email:
    type: object
    properties:
      text:
        type: string
        description: Whole email either with or withou mime format.

  TrainData:
    type: object
    properties:
      label: Label
      message: string

  Models:
    type: string
    enum:
      - NaiveBayes
      - SVM

  TrainRequest:
    type: object
    properties:
      modelType:
        description: |
          If this field is missing then every model will be updated.
        required: false
        type: Models
      data: TrainData[]

  EmailRecognitionResponse:
    type: object
    properties:
      label: Label
      percent: integer
      models: Model[]


  Model:
    type: object
    properties:
      percent: integer
      typeOfModel: string

  Label:
    type: string
    enum:
      - SPAM
      - HAM

/email-recognition:
  post:
    body: Email
    responses:
      200:
       body: EmailRecognitionResponse


/models:
  /!train:
    post:
      body: TrainRequest
      responses:
        200:
          description: Model trained
        410:
          description: typeOfModel does not exist
