#%RAML 1.0
title: "Email recognition api"
description: "Email recognition api"
version: "1.0"
protocols:
- "HTTP"
mediaType: application/json

types:
  Email:
    type: object
    properties:
      text:
        type: string
        description: Whole email either with or withou mime format.

  Models:
    type: string
    enum:
      - NaiveBayes
      - SVM

  EmailRecognitionResponse:
    type: object
    properties:
      label: Label
      models: Model[]


  Model:
    type: object
    properties:
      percent: integer
      typeOfModel: Models

  Label:
    type: string
    enum:
      - SPAM
      - HAM

/email-recognition:
  post:
    body: Email
    responses:
      200:
       body: EmailRecognitionResponse
